learning_platform_root/courses/urls.py
from django.urls import path
from .views import home

app_name = 'courses'
urlpatterns = [
	path('', home, name = 'home'),
]

learning_platform_root/learning_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from users import urls as users_urls
from courses import urls as courses_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(users_urls)),
    path('courses/', include(courses_urls)),
]

learning_platform_root/users/urls.py
from django.urls import path
from .views import profile, update_profile, community
from django.contrib.auth import views as auth_views

app_name = 'users'
urlpatterns = [
    path('profile/<int:user_id>', profile, name = 'profile'),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logged_out.html'), name = 'logout'),
    path('update/', update_profile, name = 'update_profile'),
    path('community/', community, name = 'community'),
]

learning_platform_root/courses/models.py
from django.db import models

# Create your models here.

learning_platform_root/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
	student = 1
	mentor = 2
	instructor = 3

	roles = (
		(student, 'Student'),
		(mentor, 'Mentor'),
		(instructor, 'Instructor')
		)

	role = models.PositiveSmallIntegerField(choices = roles, null = True, blank = True)
	pronouns = models.CharField(max_length = 15)
	team = models.ForeignKey('Team', null = True, on_delete = models.SET_NULL)
	buddy = models.ManyToManyField("self", blank=True)

class Team(models.Model):
	name = models.CharField(max_length = 50)

	def __str__(self):
		return self.name

learning_platform_root/users/forms.py
from django import forms
from .models import User

class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'pronouns']

learning_platform_root/courses/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def home(request):

	context = {}

	return render(request, "courses/home.html", context)

learning_platform_root/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ProfileUpdateForm
from django.contrib import messages
from .models import User

@login_required
def profile(request, user_id):
#could probably use a generic class based view for this. DetailView
	user = User.objects.get(id = user_id)

	context = {
		'own_profile' : user_id == request.user.id,
		'user': user,
		'role': user.get_role_display(),
		}

	return render(request, "users/profile.html", context)

@login_required
def update_profile(request):
	if request.method == 'POST':
		profile_form = ProfileUpdateForm(request.POST, instance = request.user)
		if profile_form.is_valid():
			profile_form.save()
			messages.success(request, 'Your profile has been updated!')
			return redirect('users:profile')

	else:
		profile_form = ProfileUpdateForm(instance=request.user)

	return render(request, 'users/update_profile.html', {
		'profile_form': profile_form
	})

@login_required
def community(request):
	buddies = request.user.buddy.all()
	context = {'buddies' : buddies}
	return render(request, 'users/community.html', context)

learning_platform_root/courses/templates/courses/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'profile/main.css' %}">

	{% if title %}
		<title>Learning Platform - {{ title }}</title>
	{% else %}
		<title>Learning Platform</title>
	{% endif %}
</head>
<body>
	<nav>
		<p><a href="{% url 'courses:home' %}">home</a><p/>
		<p><a href="{% url 'users:community' %}">community</a></p>
		<p><a href="{% url 'users:profile' request.user.id %}">profile</a></p>
	</nav>
	{% if messages %}
            {% for message in messages %}
              <div> <!-- bootstrap has a way to handle this with: class="alert alert-{{ message.tags }}" -->
                Message: {{ message }}
              </div>
            {% endfor %}
          {% endif %}
	{% block content %}{% endblock %}
</body>
</html>

learning_platform_root/courses/templates/courses/home.html
{% extends 'courses/base.html' %}
{% block content %}
	<h1>This is the homepage for {{ request.user.first_name }}</h1>
{% endblock content %}

learning_platform_root/users/templates/users/community.html
{% extends "courses/base.html" %}
{% block content %}
<h1>This is the community page</h1>

<h2>Here is/are your buddy/buddies</h2>
{% for buddy in buddies %}
	<p><a href="{% url 'users:profile' buddy.pk %}"> {{ buddy }}</p>
{% endfor %}
{% endblock content %}

learning_platform_root/users/templates/users/logged_out.html
{% extends "profile/base.html" %}
{% block content %}
<p>You have been logged out.</p>
<p><a href="/login/">Log in again</a></p>
{% endblock content %}

learning_platform_root/users/templates/users/login.html
{% extends "profile/base.html" %}
{% block content %}
<form method="POST">
	{% csrf_token %}
	<fieldset>
		<legend>Log In</legend>
		{{ form }}
	</fieldset>
	<button type="submit">Login</button>
</form>
{% endblock content %}

learning_platform_root/users/templates/users/profile.html
{% extends "courses/base.html" %}
{% block content %}

	<img id="user_photo" width = '200' height = '100' alt = 'USER PHOTO'/>
	<h3>Your Information</h3>
	<p>{{ role }}</p>
	<p>Name: {{ user.first_name }} {{ user.last_name }}</p>
	<p>Pronouns: {{ user.pronouns }}</p>
	<p>Team: {{ user.team }}</p>
	<p>Email: {{ user.email }}</p>
	{% if own_profile %}
		<p><a href="{% url 'users:update_profile' %}">Update info</a></p>
		<p><a href="{% url 'users:logout' %}">Log out</a></p>
	{% endif %}
{% endblock content %}

learning_platform_root/users/templates/users/update_profile.html
{% extends "courses/base.html" %}
{% block content %}
<form method="POST">
          {% csrf_token %}
          <fieldset class=>
              <legend>Profile Info</legend>
              {{ profile_form }}
          </fieldset>
          <div>
              <button type="submit">Update</button>
          </div>
      </form>
{% endblock content %}